version: '2'
services:
  redis-sentinel:
    image: pixul/redis-sentinel
    environment:
      SENTINEL_DOWN_AFTER_MILLISECONDS: '5000'
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=${stack_name}/${service_name}
      io.rancher.container.start_once: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    sysctls:
      net.core.somaxconn: "511"
  redis-server:
    image: pixul/redis-node
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=${stack_name}/${service_name}
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    sysctls:
      net.core.somaxconn: "511"